version: '2'
services:
    downloader-app:
        image: downloader
        external_links:
            - downloader-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/downloader
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    downloader-postgresql:
        extends:
            file: postgresql.yml
            service: downloader-postgresql
